// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'audio_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_snapshot`, `ensure_runtime`, `load_decoder`, `load_ogg_source`, `lock_audio_runtime`, `with_runtime_mut`, `with_runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioRuntime`, `AudioSource`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `channels`, `current_span_len`, `next`, `sample_rate`, `total_duration`, `try_seek`

/// Stop and forget the currently loaded source.
Future<AudioPlaybackState> audioStop() =>
    RustLib.instance.api.crateApiAudioApiAudioStop();

/// Load a file into the player and start playback at the requested position.
Future<AudioPlaybackState> audioPlayFile({
  required String path,
  required int positionMs,
}) => RustLib.instance.api.crateApiAudioApiAudioPlayFile(
  path: path,
  positionMs: positionMs,
);

/// Resume playback of the current source.
Future<AudioPlaybackState> audioResume() =>
    RustLib.instance.api.crateApiAudioApiAudioResume();

/// Pause playback.
Future<AudioPlaybackState> audioPause() =>
    RustLib.instance.api.crateApiAudioApiAudioPause();

/// Seek the current source.
Future<AudioPlaybackState> audioSeek({required int positionMs}) =>
    RustLib.instance.api.crateApiAudioApiAudioSeek(positionMs: positionMs);

/// Adjust the output volume.
Future<AudioPlaybackState> audioSetVolume({required double volume}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetVolume(volume: volume);

/// Get the latest player snapshot.
Future<AudioPlaybackState> audioGetState() =>
    RustLib.instance.api.crateApiAudioApiAudioGetState();

/// Dispose the player and release all audio resources.
Future<void> audioDispose() =>
    RustLib.instance.api.crateApiAudioApiAudioDispose();

@freezed
sealed class AudioPlaybackState with _$AudioPlaybackState {
  const factory AudioPlaybackState({
    String? currentSourcePath,
    int? durationMs,
    required int positionMs,
    required bool isPlaying,
    required bool isPaused,
    required double volume,
  }) = _AudioPlaybackState;
}
