// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.23.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../downloader.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<DownloadCallbackData> startDownload(
        {required String url,
        required String savePath,
        required String fileName,
        required int connectionCount,
        dynamic hint}) =>
    RustLib.instance.api.startDownload(
        url: url,
        savePath: savePath,
        fileName: fileName,
        connectionCount: connectionCount,
        hint: hint);

Future<void> cancelDownload({required String id, dynamic hint}) =>
    RustLib.instance.api.cancelDownload(id: id, hint: hint);
