// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ime_hotkey_api.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Starts the hook thread and popup. Calling it again restarts with the new config.
Stream<ImeHotkeyEvent> imeHotkeyStart({required ImeHotkeyConfig config}) =>
    RustLib.instance.api.crateApiImeHotkeyApiImeHotkeyStart(config: config);

/// Replaces the config of the running popup (hotkey, timings, position, texts).
Future<void> imeHotkeyUpdateConfig({required ImeHotkeyConfig config}) => RustLib
    .instance
    .api
    .crateApiImeHotkeyApiImeHotkeyUpdateConfig(config: config);

/// Stops the hook, destroys the popup and closes the event stream.
Future<void> imeHotkeyStop() =>
    RustLib.instance.api.crateApiImeHotkeyApiImeHotkeyStop();

Future<bool> imeHotkeyIsRunning() =>
    RustLib.instance.api.crateApiImeHotkeyApiImeHotkeyIsRunning();

/// Types `encoded` into the window that was in front when the popup was opened, followed by
/// Enter when `auto_send` is set. `id` must match the [`ImeHotkeyEvent::Submit`] being answered.
Future<void> imeHotkeySend({required BigInt id, required String encoded}) =>
    RustLib.instance.api.crateApiImeHotkeyApiImeHotkeySend(
      id: id,
      encoded: encoded,
    );

/// Shows `message` under the edit box and keeps the popup open (e.g. unsupported characters).
/// `busy` keeps the edit read-only while the submit is still being processed (translating);
/// otherwise the user can edit and submit again.
Future<void> imeHotkeyShowMessage({
  required String message,
  required bool isError,
  required bool busy,
}) => RustLib.instance.api.crateApiImeHotkeyApiImeHotkeyShowMessage(
  message: message,
  isError: isError,
  busy: busy,
);

/// The next key combination pressed anywhere is reported as
/// [`ImeHotkeyEvent::HotkeyCaptured`] and swallowed instead of triggering the popup.
/// Esc alone cancels without an event. Requires a running popup.
Future<void> imeHotkeyBeginCapture() =>
    RustLib.instance.api.crateApiImeHotkeyApiImeHotkeyBeginCapture();

Future<void> imeHotkeyCancelCapture() =>
    RustLib.instance.api.crateApiImeHotkeyApiImeHotkeyCancelCapture();

/// Human readable name such as `Ctrl + Alt + Space`, using the current keyboard layout.
String imeHotkeyDisplayName({required ImeHotkey hotkey}) => RustLib.instance.api
    .crateApiImeHotkeyApiImeHotkeyDisplayName(hotkey: hotkey);

class ImeHotkey {
  /// Windows virtual-key code of the non-modifier key.
  final int vk;
  final bool ctrl;
  final bool alt;
  final bool shift;
  final bool win;

  const ImeHotkey({
    required this.vk,
    required this.ctrl,
    required this.alt,
    required this.shift,
    required this.win,
  });

  @override
  int get hashCode =>
      vk.hashCode ^
      ctrl.hashCode ^
      alt.hashCode ^
      shift.hashCode ^
      win.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImeHotkey &&
          runtimeType == other.runtimeType &&
          vk == other.vk &&
          ctrl == other.ctrl &&
          alt == other.alt &&
          shift == other.shift &&
          win == other.win;
}

class ImeHotkeyConfig {
  final ImeHotkey hotkey;

  /// Only react to the hotkey while `StarCitizen.exe` owns the foreground window.
  final bool gameOnly;

  /// Pause after each typed character, in milliseconds.
  final int keyIntervalMs;

  /// Press Enter to open the chat box before typing.
  final bool openChatBeforeSend;

  /// Press Enter after typing to send the message. When false the text is only typed.
  final bool autoSend;

  /// Press Enter again after sending so the chat box stays open for the next message.
  /// Only used with `auto_send`.
  final bool reopenChatAfterSend;

  /// Last popup position in screen pixels; `None` places it near the bottom left of the
  /// game's monitor.
  final int? windowX;
  final int? windowY;

  /// Hint shown under the edit box while idle.
  final String hintText;

  /// Status text shown while the text is being encoded / typed.
  final String sendingText;

  const ImeHotkeyConfig({
    required this.hotkey,
    required this.gameOnly,
    required this.keyIntervalMs,
    required this.openChatBeforeSend,
    required this.autoSend,
    required this.reopenChatAfterSend,
    this.windowX,
    this.windowY,
    required this.hintText,
    required this.sendingText,
  });

  @override
  int get hashCode =>
      hotkey.hashCode ^
      gameOnly.hashCode ^
      keyIntervalMs.hashCode ^
      openChatBeforeSend.hashCode ^
      autoSend.hashCode ^
      reopenChatAfterSend.hashCode ^
      windowX.hashCode ^
      windowY.hashCode ^
      hintText.hashCode ^
      sendingText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImeHotkeyConfig &&
          runtimeType == other.runtimeType &&
          hotkey == other.hotkey &&
          gameOnly == other.gameOnly &&
          keyIntervalMs == other.keyIntervalMs &&
          openChatBeforeSend == other.openChatBeforeSend &&
          autoSend == other.autoSend &&
          reopenChatAfterSend == other.reopenChatAfterSend &&
          windowX == other.windowX &&
          windowY == other.windowY &&
          hintText == other.hintText &&
          sendingText == other.sendingText;
}

@freezed
sealed class ImeHotkeyEvent with _$ImeHotkeyEvent {
  const ImeHotkeyEvent._();

  /// The user pressed Enter in the popup. Answer with [`ime_hotkey_send`] (same `id`) or
  /// [`ime_hotkey_show_message`].
  const factory ImeHotkeyEvent.submit({
    required BigInt id,
    required String text,
  }) = ImeHotkeyEvent_Submit;

  /// The encoded text was typed into the game.
  const factory ImeHotkeyEvent.sent({required BigInt id}) = ImeHotkeyEvent_Sent;

  /// Typing was not started or was aborted; the popup is shown again with the text kept.
  const factory ImeHotkeyEvent.sendFailed({
    required BigInt id,
    required ImeSendFailure reason,
  }) = ImeHotkeyEvent_SendFailed;

  /// The user dragged the popup to a new place.
  const factory ImeHotkeyEvent.windowMoved({required int x, required int y}) =
      ImeHotkeyEvent_WindowMoved;

  /// Result of [`ime_hotkey_begin_capture`].
  const factory ImeHotkeyEvent.hotkeyCaptured({required ImeHotkey hotkey}) =
      ImeHotkeyEvent_HotkeyCaptured;
}

enum ImeSendFailure {
  /// The window that was in front when the hotkey was pressed is gone.
  targetWindowGone,

  /// Windows refused to bring the game window back to the front.
  focusFailed,

  /// Another window came to the front while typing; typing stopped.
  focusLost,

  /// A previous message is still being typed.
  busy,
}
