// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `hash`

/// Lists the currently connected joysticks, HID gamepads and XInput controllers.
Future<List<InputDeviceInfo>> inputListDevices() =>
    RustLib.instance.api.crateApiInputCaptureApiInputListDevices();

/// Starts background polling of all joystick-like devices and pushes detected inputs to `sink`.
/// Returns immediately. Calling it again stops the previous capture first.
Stream<InputCaptureEvent> inputCaptureStart() =>
    RustLib.instance.api.crateApiInputCaptureApiInputCaptureStart();

/// Stops the capture started by [`input_capture_start`] and closes its stream.
Future<void> inputCaptureStop() =>
    RustLib.instance.api.crateApiInputCaptureApiInputCaptureStop();

class InputCaptureEvent {
  final String deviceId;
  final String deviceName;
  final int vendorId;
  final int productId;
  final InputDeviceKind kind;

  /// Star Citizen input token without the `jsN_` / `gpN_` prefix.
  final String input;

  /// 1.0 for buttons / hats; normalized -1..1 position for axes.
  /// Button / trigger events: 1.0 on press, 0.0 on release. Axes: normalized position.
  final double value;

  const InputCaptureEvent({
    required this.deviceId,
    required this.deviceName,
    required this.vendorId,
    required this.productId,
    required this.kind,
    required this.input,
    required this.value,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      vendorId.hashCode ^
      productId.hashCode ^
      kind.hashCode ^
      input.hashCode ^
      value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputCaptureEvent &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          vendorId == other.vendorId &&
          productId == other.productId &&
          kind == other.kind &&
          input == other.input &&
          value == other.value;
}

class InputDeviceInfo {
  /// Stable id per physical device interface (hash of the HID interface path, or `xinput{slot}`).
  final String id;
  final String name;
  final int vendorId;
  final int productId;
  final InputDeviceKind kind;
  final int buttonCount;

  /// Star Citizen axis names this device exposes (`x`, `y`, `z`, `rotx`, `slider1`, ...).
  final List<String> axes;
  final int hatCount;

  const InputDeviceInfo({
    required this.id,
    required this.name,
    required this.vendorId,
    required this.productId,
    required this.kind,
    required this.buttonCount,
    required this.axes,
    required this.hatCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      vendorId.hashCode ^
      productId.hashCode ^
      kind.hashCode ^
      buttonCount.hashCode ^
      axes.hashCode ^
      hatCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputDeviceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          vendorId == other.vendorId &&
          productId == other.productId &&
          kind == other.kind &&
          buttonCount == other.buttonCount &&
          axes == other.axes &&
          hatCount == other.hatCount;
}

enum InputDeviceKind {
  /// HID joystick / throttle / pedals (generic desktop usage 0x04).
  joystick,

  /// Non-XInput HID gamepad (generic desktop usage 0x05).
  gamepad,

  /// Xbox-compatible controller read through XInput.
  xInput,
}
