// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cancelled`, `done`, `error`, `to_upgrader_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

List<String> p4KUpgraderDefaultObjectPathTemplates() => RustLib.instance.api
    .crateApiP4KUpgraderApiP4KUpgraderDefaultObjectPathTemplates();

Future<P4kUpgraderEstimateReport> p4KUpgraderEstimate({
  required P4kUpgraderConfig config,
}) => RustLib.instance.api.crateApiP4KUpgraderApiP4KUpgraderEstimate(
  config: config,
);

Future<void> p4KUpgraderVerify({required P4kUpgraderConfig config}) => RustLib
    .instance
    .api
    .crateApiP4KUpgraderApiP4KUpgraderVerify(config: config);

Future<String> p4KUpgraderUpdate({required P4kUpgraderConfig config}) => RustLib
    .instance
    .api
    .crateApiP4KUpgraderApiP4KUpgraderUpdate(config: config);

Stream<P4kUpgraderProgressEvent> p4KUpgraderUpdateWithProgress({
  required P4kUpgraderConfig config,
}) => RustLib.instance.api.crateApiP4KUpgraderApiP4KUpgraderUpdateWithProgress(
  config: config,
);

void p4KUpgraderSetDownloadThreads({required BigInt threads}) => RustLib
    .instance
    .api
    .crateApiP4KUpgraderApiP4KUpgraderSetDownloadThreads(threads: threads);

void p4KUpgraderPause() =>
    RustLib.instance.api.crateApiP4KUpgraderApiP4KUpgraderPause();

void p4KUpgraderResume() =>
    RustLib.instance.api.crateApiP4KUpgraderApiP4KUpgraderResume();

void p4KUpgraderCancel() =>
    RustLib.instance.api.crateApiP4KUpgraderApiP4KUpgraderCancel();

void p4KUpgraderClearManifestCache() =>
    RustLib.instance.api.crateApiP4KUpgraderApiP4KUpgraderClearManifestCache();

class P4kUpgraderConfig {
  final String manifestSource;
  final List<String> mirrorBases;
  final List<String> officialBases;
  final String p4KBaseUrl;
  final String p4KBaseVerificationUrl;
  final List<String> objectPathTemplates;
  final String requestCookie;
  final String rsiToken;
  final String cacheDir;
  final String gameDir;
  final bool updateP4K;
  final bool updateLooseFiles;
  final bool inplaceUpdateP4K;
  final bool fallbackRebuildOnInplaceVerifyFailure;
  final bool replaceExistingP4K;
  final bool verifyAfterAssemble;
  final bool verifyCigStructure;
  final BigInt? maxEntries;

  const P4kUpgraderConfig({
    required this.manifestSource,
    required this.mirrorBases,
    required this.officialBases,
    required this.p4KBaseUrl,
    required this.p4KBaseVerificationUrl,
    required this.objectPathTemplates,
    required this.requestCookie,
    required this.rsiToken,
    required this.cacheDir,
    required this.gameDir,
    required this.updateP4K,
    required this.updateLooseFiles,
    required this.inplaceUpdateP4K,
    required this.fallbackRebuildOnInplaceVerifyFailure,
    required this.replaceExistingP4K,
    required this.verifyAfterAssemble,
    required this.verifyCigStructure,
    this.maxEntries,
  });

  @override
  int get hashCode =>
      manifestSource.hashCode ^
      mirrorBases.hashCode ^
      officialBases.hashCode ^
      p4KBaseUrl.hashCode ^
      p4KBaseVerificationUrl.hashCode ^
      objectPathTemplates.hashCode ^
      requestCookie.hashCode ^
      rsiToken.hashCode ^
      cacheDir.hashCode ^
      gameDir.hashCode ^
      updateP4K.hashCode ^
      updateLooseFiles.hashCode ^
      inplaceUpdateP4K.hashCode ^
      fallbackRebuildOnInplaceVerifyFailure.hashCode ^
      replaceExistingP4K.hashCode ^
      verifyAfterAssemble.hashCode ^
      verifyCigStructure.hashCode ^
      maxEntries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P4kUpgraderConfig &&
          runtimeType == other.runtimeType &&
          manifestSource == other.manifestSource &&
          mirrorBases == other.mirrorBases &&
          officialBases == other.officialBases &&
          p4KBaseUrl == other.p4KBaseUrl &&
          p4KBaseVerificationUrl == other.p4KBaseVerificationUrl &&
          objectPathTemplates == other.objectPathTemplates &&
          requestCookie == other.requestCookie &&
          rsiToken == other.rsiToken &&
          cacheDir == other.cacheDir &&
          gameDir == other.gameDir &&
          updateP4K == other.updateP4K &&
          updateLooseFiles == other.updateLooseFiles &&
          inplaceUpdateP4K == other.inplaceUpdateP4K &&
          fallbackRebuildOnInplaceVerifyFailure ==
              other.fallbackRebuildOnInplaceVerifyFailure &&
          replaceExistingP4K == other.replaceExistingP4K &&
          verifyAfterAssemble == other.verifyAfterAssemble &&
          verifyCigStructure == other.verifyCigStructure &&
          maxEntries == other.maxEntries;
}

class P4kUpgraderEstimateEntry {
  final String name;
  final String sha256;
  final BigInt compressedSize;

  const P4kUpgraderEstimateEntry({
    required this.name,
    required this.sha256,
    required this.compressedSize,
  });

  @override
  int get hashCode => name.hashCode ^ sha256.hashCode ^ compressedSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P4kUpgraderEstimateEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sha256 == other.sha256 &&
          compressedSize == other.compressedSize;
}

class P4kUpgraderEstimateReport {
  final BigInt manifestEntries;
  final bool baseDownloadRequired;
  final BigInt baseDownloadBytes;
  final BigInt p4KEntriesRequiringDownload;
  final BigInt looseEntriesRequiringDownload;
  final BigInt totalEntriesRequiringDownload;
  final BigInt payloadDownloadBytes;
  final double payloadDownloadGbDecimal;
  final double payloadDownloadGib;

  /// E: static "full-download" reference value — the manifest's
  /// cumulative non-loose compressed_size. Used by the UI for the
  /// "总下载大小" display row. NOT diffed against cached bytes; the
  /// differential lives in `payload_download_bytes` (unchanged).
  final BigInt totalDownloadBytes;
  final List<P4kUpgraderEstimateEntry> entries;

  const P4kUpgraderEstimateReport({
    required this.manifestEntries,
    required this.baseDownloadRequired,
    required this.baseDownloadBytes,
    required this.p4KEntriesRequiringDownload,
    required this.looseEntriesRequiringDownload,
    required this.totalEntriesRequiringDownload,
    required this.payloadDownloadBytes,
    required this.payloadDownloadGbDecimal,
    required this.payloadDownloadGib,
    required this.totalDownloadBytes,
    required this.entries,
  });

  @override
  int get hashCode =>
      manifestEntries.hashCode ^
      baseDownloadRequired.hashCode ^
      baseDownloadBytes.hashCode ^
      p4KEntriesRequiringDownload.hashCode ^
      looseEntriesRequiringDownload.hashCode ^
      totalEntriesRequiringDownload.hashCode ^
      payloadDownloadBytes.hashCode ^
      payloadDownloadGbDecimal.hashCode ^
      payloadDownloadGib.hashCode ^
      totalDownloadBytes.hashCode ^
      entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P4kUpgraderEstimateReport &&
          runtimeType == other.runtimeType &&
          manifestEntries == other.manifestEntries &&
          baseDownloadRequired == other.baseDownloadRequired &&
          baseDownloadBytes == other.baseDownloadBytes &&
          p4KEntriesRequiringDownload == other.p4KEntriesRequiringDownload &&
          looseEntriesRequiringDownload ==
              other.looseEntriesRequiringDownload &&
          totalEntriesRequiringDownload ==
              other.totalEntriesRequiringDownload &&
          payloadDownloadBytes == other.payloadDownloadBytes &&
          payloadDownloadGbDecimal == other.payloadDownloadGbDecimal &&
          payloadDownloadGib == other.payloadDownloadGib &&
          totalDownloadBytes == other.totalDownloadBytes &&
          entries == other.entries;
}

class P4kUpgraderProgressEvent {
  final String phase;
  final String name;
  final BigInt current;
  final BigInt total;
  final BigInt downloadedBytes;
  final BigInt totalBytes;
  final BigInt activeDownloads;
  final BigInt threadLimit;
  final String message;

  const P4kUpgraderProgressEvent({
    required this.phase,
    required this.name,
    required this.current,
    required this.total,
    required this.downloadedBytes,
    required this.totalBytes,
    required this.activeDownloads,
    required this.threadLimit,
    required this.message,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      name.hashCode ^
      current.hashCode ^
      total.hashCode ^
      downloadedBytes.hashCode ^
      totalBytes.hashCode ^
      activeDownloads.hashCode ^
      threadLimit.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is P4kUpgraderProgressEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          name == other.name &&
          current == other.current &&
          total == other.total &&
          downloadedBytes == other.downloadedBytes &&
          totalBytes == other.totalBytes &&
          activeDownloads == other.activeDownloads &&
          threadLimit == other.threadLimit &&
          message == other.message;
}
