// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.25.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<String> startProcess(
        {required String executable,
        required List<String> arguments,
        required String workingDirectory,
        dynamic hint}) =>
    RustLib.instance.api.startProcess(
        executable: executable,
        arguments: arguments,
        workingDirectory: workingDirectory,
        hint: hint);
