// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get the system OS name
String getSystemName() =>
    RustLib.instance.api.crateApiSystemInfoGetSystemName();

/// Get the CPU name/model
String getCpuName() => RustLib.instance.api.crateApiSystemInfoGetCpuName();

/// Get the system memory size in GB
BigInt getSystemMemorySizeGb() =>
    RustLib.instance.api.crateApiSystemInfoGetSystemMemorySizeGb();

/// Get the number of logical processors
int getNumberOfLogicalProcessors() =>
    RustLib.instance.api.crateApiSystemInfoGetNumberOfLogicalProcessors();

bool checkNvmePatchStatus() =>
    RustLib.instance.api.crateApiSystemInfoCheckNvmePatchStatus();

/// Get list of process IDs by name
Uint32List getProcessIdsByName({required String processName}) => RustLib
    .instance
    .api
    .crateApiSystemInfoGetProcessIdsByName(processName: processName);

/// Kill processes by PID
int killProcessesByPids({required List<int> pids}) =>
    RustLib.instance.api.crateApiSystemInfoKillProcessesByPids(pids: pids);
