// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'unp4k_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_preview_candidates`, `build_wav_from_pcm`, `collect_dds_part_paths`, `collect_dds_parts`, `compute_dds_mip_sizes`, `compute_waveform_from_pcm`, `compute_waveform_from_wav`, `dds_base_path`, `dds_block_bytes_dxgi`, `dds_block_bytes`, `dds_payload_layout`, `decode_dds_image`, `decode_image_for_preview`, `decode_uncompressed_dds`, `dos_datetime_to_millis`, `ensure_files_loaded`, `estimate_duration_from_wav`, `extract_masked_component`, `has_dds_signature`, `le_u32`, `model_dcb_cache_key`, `normalize_p4k_path`, `normalize_slashes`, `p4k_get_entry`, `reconstruct_dds_stream`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 打开 P4K 文件（仅打开，不读取文件列表）
Future<void> p4KOpen({required String p4KPath}) =>
    RustLib.instance.api.crateApiUnp4KApiP4KOpen(p4KPath: p4KPath);

Future<ArcDataForge> p4KGetOrLoadModelDcb({required String p4KPath}) =>
    RustLib.instance.api.crateApiUnp4KApiP4KGetOrLoadModelDcb(p4KPath: p4KPath);

Future<void> p4KClearModelDcbCache() =>
    RustLib.instance.api.crateApiUnp4KApiP4KClearModelDcbCache();

/// 获取文件数量（会触发文件列表加载）
Future<BigInt> p4KGetFileCount() =>
    RustLib.instance.api.crateApiUnp4KApiP4KGetFileCount();

/// 获取所有文件列表
Future<List<P4kFileItem>> p4KGetAllFiles() =>
    RustLib.instance.api.crateApiUnp4KApiP4KGetAllFiles();

/// 提取文件到内存
Future<Uint8List> p4KExtractToMemory({required String filePath}) =>
    RustLib.instance.api.crateApiUnp4KApiP4KExtractToMemory(filePath: filePath);

/// 提取并解码图片为 PNG（用于 UI 预览）
/// 对 .dds 会自动尝试 .dds.0 ~ .dds.15 的层级文件
Future<Uint8List> p4KPreviewImagePng({required String filePath}) =>
    RustLib.instance.api.crateApiUnp4KApiP4KPreviewImagePng(filePath: filePath);

/// 提取 DDS 文件并转换为 PNG，返回 PNG 字节和调试信息
Future<(Uint8List, DdsPngDebug)> p4KExtractDdsAsPng({
  required String filePath,
}) =>
    RustLib.instance.api.crateApiUnp4KApiP4KExtractDdsAsPng(filePath: filePath);

/// 调试 DDS 分片信息
Future<DdsDebugInfo> p4KDebugDdsParts({required String filePath}) =>
    RustLib.instance.api.crateApiUnp4KApiP4KDebugDdsParts(filePath: filePath);

/// 提取文件到磁盘
Future<void> p4KExtractToDisk({
  required String filePath,
  required String outputPath,
}) => RustLib.instance.api.crateApiUnp4KApiP4KExtractToDisk(
  filePath: filePath,
  outputPath: outputPath,
);

/// 内置 WEM -> OGG 转换（用于预览播放，不依赖外部工具）
Future<void> p4KDecodeWemToOgg({
  required String inputPath,
  required String outputPath,
}) => RustLib.instance.api.crateApiUnp4KApiP4KDecodeWemToOgg(
  inputPath: inputPath,
  outputPath: outputPath,
);

/// 内置 WEM -> OGG 预览转换（估算中段并仅输出短片段）
Future<void> p4KDecodeWemToOggPreview({
  required String inputPath,
  required String outputPath,
  required int clipSeconds,
}) => RustLib.instance.api.crateApiUnp4KApiP4KDecodeWemToOggPreview(
  inputPath: inputPath,
  outputPath: outputPath,
  clipSeconds: clipSeconds,
);

/// 将 OGG 转为 WAV（导出时用于复用缓存）
Future<void> p4KDecodeOggToWav({
  required String inputPath,
  required String outputPath,
}) => RustLib.instance.api.crateApiUnp4KApiP4KDecodeOggToWav(
  inputPath: inputPath,
  outputPath: outputPath,
);

/// 内置 WEM(PCM) -> WAV 转换（用于预览播放或导出兜底，不依赖外部工具）
Future<void> p4KDecodeWemToWav({
  required String inputPath,
  required String outputPath,
}) => RustLib.instance.api.crateApiUnp4KApiP4KDecodeWemToWav(
  inputPath: inputPath,
  outputPath: outputPath,
);

/// 内置 WEM -> WAV 预览转换（估算中段并仅输出短片段，导出兜底用）
Future<void> p4KDecodeWemToWavPreview({
  required String inputPath,
  required String outputPath,
  required int clipSeconds,
}) => RustLib.instance.api.crateApiUnp4KApiP4KDecodeWemToWavPreview(
  inputPath: inputPath,
  outputPath: outputPath,
  clipSeconds: clipSeconds,
);

/// 取消正在进行的 WEM 解码任务（通过提升全局请求 id）
Future<void> p4KCancelWemDecode() =>
    RustLib.instance.api.crateApiUnp4KApiP4KCancelWemDecode();

/// 流式解码 WEM 到内存，返回进度和波形数据
/// 每2秒发送一次进度更新，支持流式播放
Stream<WemDecodeProgress> p4KDecodeWemToWavStream({
  required String inputPath,
}) => RustLib.instance.api.crateApiUnp4KApiP4KDecodeWemToWavStream(
  inputPath: inputPath,
);

/// In-memory variant of `p4k_decode_wem_to_wav_stream` — accepts raw WEM bytes instead of a file path.
Stream<WemDecodeProgress> p4KDecodeWemBytesToWavStream({
  required List<int> wemBytes,
}) => RustLib.instance.api.crateApiUnp4KApiP4KDecodeWemBytesToWavStream(
  wemBytes: wemBytes,
);

/// 关闭 P4K 读取器
Future<void> p4KClose() => RustLib.instance.api.crateApiUnp4KApiP4KClose();

/// 检查数据是否为 DataForge/DCB 格式
Future<bool> dcbIsDataforge({required List<int> data}) =>
    RustLib.instance.api.crateApiUnp4KApiDcbIsDataforge(data: data);

/// 从内存数据打开 DCB 文件
Future<void> dcbOpen({required List<int> data}) =>
    RustLib.instance.api.crateApiUnp4KApiDcbOpen(data: data);

/// 获取 DCB 记录数量
Future<BigInt> dcbGetRecordCount() =>
    RustLib.instance.api.crateApiUnp4KApiDcbGetRecordCount();

/// 获取所有 DCB 记录路径列表
Future<List<DcbRecordItem>> dcbGetRecordList() =>
    RustLib.instance.api.crateApiUnp4KApiDcbGetRecordList();

/// 根据路径获取单条记录的 XML
Future<String> dcbRecordToXml({required String path}) =>
    RustLib.instance.api.crateApiUnp4KApiDcbRecordToXml(path: path);

/// 根据索引获取单条记录的 XML
Future<String> dcbRecordToXmlByIndex({required BigInt index}) =>
    RustLib.instance.api.crateApiUnp4KApiDcbRecordToXmlByIndex(index: index);

/// 全文搜索 DCB 记录
Future<List<DcbSearchResult>> dcbSearchAll({required String query}) =>
    RustLib.instance.api.crateApiUnp4KApiDcbSearchAll(query: query);

/// 导出 DCB 到磁盘
/// merge: true = 合并为单个 XML，false = 分离为多个 XML 文件
Future<void> dcbExportToDisk({
  required String outputPath,
  required String dcbPath,
  required bool merge,
}) => RustLib.instance.api.crateApiUnp4KApiDcbExportToDisk(
  outputPath: outputPath,
  dcbPath: dcbPath,
  merge: merge,
);

/// 关闭 DCB 读取器
Future<void> dcbClose() => RustLib.instance.api.crateApiUnp4KApiDcbClose();

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < DataForge >>>
abstract class ArcDataForge implements RustOpaqueInterface {}

/// DCB 记录项信息
@freezed
sealed class DcbRecordItem with _$DcbRecordItem {
  const factory DcbRecordItem({required String path, required BigInt index}) =
      _DcbRecordItem;
}

@freezed
sealed class DcbSearchMatch with _$DcbSearchMatch {
  const factory DcbSearchMatch({
    required BigInt lineNumber,
    required String lineContent,
  }) = _DcbSearchMatch;
}

/// 全文搜索 DCB 记录
/// 返回匹配的记录路径和预览摘要
@freezed
sealed class DcbSearchResult with _$DcbSearchResult {
  const factory DcbSearchResult({
    required String path,
    required BigInt index,
    required List<DcbSearchMatch> matches,
  }) = _DcbSearchResult;
}

/// DDS 调试信息
@freezed
sealed class DdsDebugInfo with _$DdsDebugInfo {
  const factory DdsDebugInfo({
    required String requestedPath,
    required String basePath,
    required String baseKey,
    String? baseReal,
    required BigInt partCount,
    required List<DdsPartInfo> parts,
  }) = _DdsDebugInfo;
}

/// DDS 分片信息
@freezed
sealed class DdsPartInfo with _$DdsPartInfo {
  const factory DdsPartInfo({required BigInt index, required String path}) =
      _DdsPartInfo;
}

/// DDS 转 PNG 调试信息
@freezed
sealed class DdsPngDebug with _$DdsPngDebug {
  const DdsPngDebug._();
  const factory DdsPngDebug({
    required String requestedPath,
    required String basePath,
    required BigInt partCount,
    required bool reconstructed,
    required String decodeMode,
    required int width,
    required int height,
  }) = _DdsPngDebug;
  static Future<DdsPngDebug> default_() =>
      RustLib.instance.api.crateApiUnp4KApiDdsPngDebugDefault();
}

/// P4K 文件项信息
@freezed
sealed class P4kFileItem with _$P4kFileItem {
  const factory P4kFileItem({
    required String name,
    required bool isDirectory,
    required BigInt size,
    required BigInt compressedSize,
    required PlatformInt64 dateModified,
  }) = _P4kFileItem;
}

@freezed
sealed class WemDecodeProgress with _$WemDecodeProgress {
  const factory WemDecodeProgress({
    required double progress,
    Float64List? waveform,
    int? durationMs,
    required bool isComplete,
    String? error,
    Int16List? pcmChunk,
    int? sampleRate,
    int? channels,
    required int chunkIndex,
  }) = _WemDecodeProgress;
}
