// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'unp4k_model_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `preview_session_exists`, `session_bg_color`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PREVIEW_SESSION_STATUS`, `PreviewSessionStatus`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `from`, `initialize`

/// Initialize the OpenGL context for model rendering.
/// Should be called once at application startup before any model rendering.
/// Returns true if context was initialized, false if already initialized.
Future<bool> p4KModelInitContext() =>
    RustLib.instance.api.crateApiUnp4KModelApiP4KModelInitContext();

Future<bool> p4KModelIsSupported({required String filePath}) => RustLib
    .instance
    .api
    .crateApiUnp4KModelApiP4KModelIsSupported(filePath: filePath);

Future<ModelConvertResult> p4KModelConvertToGlb({
  required String p4KPath,
  required String modelPath,
  required String outputDir,
  ModelConvertOptions? options,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelConvertToGlb(
  p4KPath: p4KPath,
  modelPath: modelPath,
  outputDir: outputDir,
  options: options,
);

Future<ModelConvertBytesResult> p4KModelConvertToGlbBytes({
  required String p4KPath,
  required String modelPath,
  ModelConvertOptions? options,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelConvertToGlbBytes(
  p4KPath: p4KPath,
  modelPath: modelPath,
  options: options,
);

Future<LocalBatchConvertResult> p4KModelConvertLocalBatchAndMerge({
  required String assetRoot,
  required String outputDir,
  ModelConvertOptions? options,
}) =>
    RustLib.instance.api.crateApiUnp4KModelApiP4KModelConvertLocalBatchAndMerge(
      assetRoot: assetRoot,
      outputDir: outputDir,
      options: options,
    );

Future<ModelRenderResult> p4KModelRenderPreview({
  required String glbPath,
  required int width,
  required int height,
  required double pitch,
  required double yaw,
  required double roll,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelRenderPreview(
  glbPath: glbPath,
  width: width,
  height: height,
  pitch: pitch,
  yaw: yaw,
  roll: roll,
);

Future<SessionCreateResult> p4KModelSessionCreate({
  required String glbPath,
  required int width,
  required int height,
  Float32List? bgColor,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelSessionCreate(
  glbPath: glbPath,
  width: width,
  height: height,
  bgColor: bgColor,
);

Future<SessionCreateResult> p4KModelSessionCreateFromBytes({
  required List<int> glbBytes,
  required int width,
  required int height,
  Float32List? bgColor,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelSessionCreateFromBytes(
  glbBytes: glbBytes,
  width: width,
  height: height,
  bgColor: bgColor,
);

Future<SessionCreateResult> p4KModelSessionCreateFromP4K({
  required String p4KPath,
  required String modelPath,
  required int width,
  required int height,
  Float32List? bgColor,
  ModelConvertOptions? options,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelSessionCreateFromP4K(
  p4KPath: p4KPath,
  modelPath: modelPath,
  width: width,
  height: height,
  bgColor: bgColor,
  options: options,
);

Future<SessionStartResult> p4KModelSessionStartFromP4K({
  required String p4KPath,
  required String modelPath,
  required int width,
  required int height,
  Float32List? bgColor,
  ModelConvertOptions? options,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelSessionStartFromP4K(
  p4KPath: p4KPath,
  modelPath: modelPath,
  width: width,
  height: height,
  bgColor: bgColor,
  options: options,
);

Future<SessionStatusResult> p4KModelSessionStatus({
  required String sessionId,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelSessionStatus(
  sessionId: sessionId,
);

Future<ModelRenderResult> p4KModelSessionRender({
  required String sessionId,
  required double cameraX,
  required double cameraY,
  required double cameraZ,
  required double targetX,
  required double targetY,
  required double targetZ,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelSessionRender(
  sessionId: sessionId,
  cameraX: cameraX,
  cameraY: cameraY,
  cameraZ: cameraZ,
  targetX: targetX,
  targetY: targetY,
  targetZ: targetZ,
);

Future<ModelRenderResult> p4KModelSessionRenderResized({
  required String sessionId,
  required int width,
  required int height,
  required double cameraX,
  required double cameraY,
  required double cameraZ,
  required double targetX,
  required double targetY,
  required double targetZ,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelSessionRenderResized(
  sessionId: sessionId,
  width: width,
  height: height,
  cameraX: cameraX,
  cameraY: cameraY,
  cameraZ: cameraZ,
  targetX: targetX,
  targetY: targetY,
  targetZ: targetZ,
);

Future<bool> p4KModelSessionRelease({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiUnp4KModelApiP4KModelSessionRelease(sessionId: sessionId);

Future<bool> p4KModelSessionExists({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiUnp4KModelApiP4KModelSessionExists(sessionId: sessionId);

@freezed
sealed class AssemblyGraphStats with _$AssemblyGraphStats {
  const factory AssemblyGraphStats({
    required int nodes,
    required int geometryNodes,
    required int objectContainers,
    required int roots,
  }) = _AssemblyGraphStats;
}

@freezed
sealed class LocalBatchConvertResult with _$LocalBatchConvertResult {
  const factory LocalBatchConvertResult({
    required bool success,
    String? mergedOutputPath,
    String? assemblyManifestPath,
    String? assemblyReportPath,
    required int successCount,
    required int emptyCount,
    required int failedCount,
    required List<String> warnings,
    required List<LocalBatchFileResult> files,
    required String sourceMode,
    required AssemblyGraphStats assemblyGraphStats,
    required List<String> fallbackReasonByFile,
    String? errorCode,
    String? errorMessage,
  }) = _LocalBatchConvertResult;
}

@freezed
sealed class LocalBatchFileResult with _$LocalBatchFileResult {
  const factory LocalBatchFileResult({
    required String modelPath,
    String? outputPath,
    required bool hasGeometry,
    String? errorCode,
    String? errorMessage,
    required List<String> warnings,
    required String sourceMode,
    String? fallbackReason,
  }) = _LocalBatchFileResult;
}

@freezed
sealed class ModelConvertBytesResult with _$ModelConvertBytesResult {
  const factory ModelConvertBytesResult({
    required bool success,
    Uint8List? glbBytes,
    String? errorCode,
    String? errorMessage,
    required List<String> warnings,
  }) = _ModelConvertBytesResult;
}

@freezed
sealed class ModelConvertOptions with _$ModelConvertOptions {
  const factory ModelConvertOptions({
    required bool embedTextures,
    required bool overwrite,
    int? maxTextureSize,
  }) = _ModelConvertOptions;
}

@freezed
sealed class ModelConvertResult with _$ModelConvertResult {
  const factory ModelConvertResult({
    required bool success,
    String? outputPath,
    String? errorCode,
    String? errorMessage,
    required List<String> warnings,
  }) = _ModelConvertResult;
}

@freezed
sealed class ModelRenderResult with _$ModelRenderResult {
  const factory ModelRenderResult({
    required bool success,
    required int width,
    required int height,
    Uint8List? rgbaData,
    String? errorMessage,
  }) = _ModelRenderResult;
}

@freezed
sealed class SessionCreateResult with _$SessionCreateResult {
  const factory SessionCreateResult({
    required bool success,
    String? sessionId,
    required double modelRadius,
    String? errorMessage,
  }) = _SessionCreateResult;
}

@freezed
sealed class SessionStartResult with _$SessionStartResult {
  const factory SessionStartResult({
    required bool success,
    String? sessionId,
    String? errorMessage,
  }) = _SessionStartResult;
}

@freezed
sealed class SessionStatusResult with _$SessionStatusResult {
  const factory SessionStatusResult({
    required bool exists,
    required bool ready,
    required bool failed,
    required String stage,
    required double modelRadius,
    String? errorMessage,
  }) = _SessionStatusResult;
}
