// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'unp4k_model_api.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

Future<bool> p4KModelIsSupported({required String filePath}) => RustLib
    .instance
    .api
    .crateApiUnp4KModelApiP4KModelIsSupported(filePath: filePath);

Future<ModelConvertResult> p4KModelConvertToGlb({
  required String p4KPath,
  required String modelPath,
  required String outputDir,
  ModelConvertOptions? options,
}) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelConvertToGlb(
  p4KPath: p4KPath,
  modelPath: modelPath,
  outputDir: outputDir,
  options: options,
);

@freezed
sealed class ModelConvertOptions with _$ModelConvertOptions {
  const factory ModelConvertOptions({
    required bool embedTextures,
    required bool overwrite,
    int? maxTextureSize,
  }) = _ModelConvertOptions;
}

@freezed
sealed class ModelConvertResult with _$ModelConvertResult {
  const factory ModelConvertResult({
    required bool success,
    String? outputPath,
    String? errorCode,
    String? errorMessage,
    required List<String> warnings,
  }) = _ModelConvertResult;
}
