// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'unp4k_model_api.freezed.dart';

            // These functions are ignored because they are not marked as `pub`: `collect_batch_model_candidates`, `is_empty_geometry_error`, `to_display_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`


            Future<bool>  p4KModelIsSupported({required String filePath }) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelIsSupported(filePath: filePath);

Future<ModelConvertResult>  p4KModelConvertToGlb({required String p4KPath , required String modelPath , required String outputDir , ModelConvertOptions? options }) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelConvertToGlb(p4KPath: p4KPath, modelPath: modelPath, outputDir: outputDir, options: options);

Future<LocalBatchConvertResult>  p4KModelConvertLocalBatchAndMerge({required String assetRoot , required String outputDir , ModelConvertOptions? options }) => RustLib.instance.api.crateApiUnp4KModelApiP4KModelConvertLocalBatchAndMerge(assetRoot: assetRoot, outputDir: outputDir, options: options);

            @freezed
sealed class AssemblyGraphStats with _$AssemblyGraphStats  {

                const factory AssemblyGraphStats({ required  int nodes, required  int geometryNodes, required  int objectContainers, required  int roots,}) = _AssemblyGraphStats;



            }

@freezed
sealed class LocalBatchConvertResult with _$LocalBatchConvertResult  {

                const factory LocalBatchConvertResult({ required  bool success,  String? mergedOutputPath,  String? assemblyManifestPath,  String? assemblyReportPath, required  int successCount, required  int emptyCount, required  int failedCount, required  List<String> warnings, required  List<LocalBatchFileResult> files, required  String sourceMode, required  AssemblyGraphStats assemblyGraphStats, required  List<String> fallbackReasonByFile,  String? errorCode,  String? errorMessage,}) = _LocalBatchConvertResult;



            }

@freezed
sealed class LocalBatchFileResult with _$LocalBatchFileResult  {

                const factory LocalBatchFileResult({ required  String modelPath,  String? outputPath, required  bool hasGeometry,  String? errorCode,  String? errorMessage, required  List<String> warnings, required  String sourceMode,  String? fallbackReason,}) = _LocalBatchFileResult;



            }

@freezed
sealed class ModelConvertOptions with _$ModelConvertOptions  {

                const factory ModelConvertOptions({ required  bool embedTextures, required  bool overwrite,  int? maxTextureSize,}) = _ModelConvertOptions;



            }

@freezed
sealed class ModelConvertResult with _$ModelConvertResult  {

                const factory ModelConvertResult({ required  bool success,  String? outputPath,  String? errorCode,  String? errorMessage, required  List<String> warnings,}) = _ModelConvertResult;



            }