name: "Windows Nightly Build"
on:
    schedule:
        - cron: "0 0 * * *" # every day at midnight
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
               channel: 'stable'
            - run: flutter --version
            - name: Set up Rust
              uses: dtolnay/rust-toolchain@stable
            - run: rustup --version  
            - run: cargo --version
            - name: Set up LLVM
              uses: KyleMayes/install-llvm-action@v1
              with:
               version: "10.0"
            - run: llvm-config --version
            - name: Set up Flutter rust bridge
              run: cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.0'
            - name: Flutter pub get
              run: flutter pub get  
            - name: Rust bridge generate
              run: flutter_rust_bridge_codegen generate
            - name: Flutter build Windows
              run: flutter build windows
            - name: Archive build
              uses: actions/upload-artifact@v4
              with:
                name: windows
                path: build/windows/x64/runner/Release