name: "Windows Nightly Build"
on:
    schedule:
        - cron: "0 0 * * *" # every day at midnight
    workflow_dispatch:    
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                cache: true
                cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
                cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
                pub-cache-key: 'flutter-pub:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache of dart pub get dependencies
                pub-cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
            - run: flutter --version            
            - name: Set up Rust
              uses: dtolnay/rust-toolchain@stable
            - run: rustup --version  
            - run: cargo --version
            - name: Set up LLVM
              uses: KyleMayes/install-llvm-action@v1
              with:
               version: "17.0.2"
            - name: Clean Pub Git Cache
              run: |
                 if (Test-Path "C:\Users\runneradmin\.pub-cache\git\") {
                   Remove-Item -Path "C:\Users\runneradmin\.pub-cache\git\*" -Recurse -Force
                 }
              shell: powershell
            - name: Flutter pub get
              run: flutter pub get  
            - name: Set up Flutter rust bridge
              run: cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.0'  
            - name: Rust bridge generate
              run: flutter_rust_bridge_codegen generate
            - name: flutter gen l10n
              run: flutter pub run intl_utils:generate  
            - name: Flutter build Windows
              run: flutter build windows
            - name: Archive build
              uses: actions/upload-artifact@v4
              with:
                name: windows
                path: build/windows/x64/runner/Release
                